apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: postgresql-config
data:
  POSTGRES_USER: dbuser
  POSTGRES_PASSWORD: dbconnect
  POSTGRES_DB: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest 
        ports: 
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgresql-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes: 
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
---
apiVersion: v1 
kind: Service 
metadata:
 name: postgres 
spec:
  selector: 
    app: postgres 
  ports: 
    - protocol: TCP
      port: 5432
      targetPort: 5432